In [1]:
import numpy as np
import joblib

In [3]:
model=joblib.load('tensile_model.obj')

In [4]:
test_1=np.array([[0.16,0.41,1.48,0.014,0.01,0.02,0.02,0.01,0.03,0.08,0.033,0.0079,0,500]])

In [5]:
model.predict(test_1)

array([440.6])

Actual: 450

In [6]:
test_2=np.array([[0.22,0.22,1.24,0.021,0.008,0.03,0.05,0.017,0.01,0.005,0.005,0.0116,0.0017,350]])

In [7]:
model.predict(test_2)

array([654.8])

Actual: 632

C	Si	Mn	P	S	Ni	Cr	Mo	Cu	V	Al	N	Nb + Ta	Tensile_Strength	Temperature

(0.23 wt% C, 3.1 wt% Cr, 1.2 wt% Mo,
11.1 wt% Ni, 3.4 wt% Co) that can be heat
treated to 1930 to 2070 or 2000 to 2140 MPa

In [13]:
test_3=np.array([[0.23,0,0,0,0,11.1,3.1,1.2,0,0,0,0,0,650]])

In [14]:
model.predict(test_3)

array([355.6])